db = db.getSiblingDB('fastgpt');
db.model_datas.deleteMany({});
print('Deleted old models');
db.model_datas.insertOne({
  _id: '1',
  model: 'glm-4',
  name: 'GLM-4',
  avatar: '/imgs/model/openai.svg',
  maxContext: 128000,
  maxResponse: 4000,
  quoteMaxToken: 3000,
  maxTemperature: 1.2,
  charsPointsPrice: 0,
  censor: true,
  vision: false,
  datasetProcess: true,
  usedInClassify: true,
  usedInExtractFields: true,
  usedInToolCall: true,
  usedInQueryExtension: true,
  toolChoice: true,
  functionCall: true,
  dbModel: 'glm-4',
  dbMaxToken: 4000,
  dbReqUrl: ''
});
db.model_datas.insertOne({
  _id: '2',
  model: 'qwen3:8b',
  name: '通义千问3-8B (Ollama)',
  avatar: '/imgs/model/openai.svg',
  maxContext: 32768,
  maxResponse: 8000,
  quoteMaxToken: 3000,
  maxTemperature: 1.2,
  charsPointsPrice: 0,
  censor: true,
  vision: false,
  datasetProcess: true,
  usedInClassify: true,
  usedInExtractFields: true,
  usedInToolCall: true,
  usedInQueryExtension: true,
  toolChoice: true,
  functionCall: true,
  dbModel: 'qwen3:8b',
  dbMaxToken: 8000,
  dbReqUrl: 'http://localhost:11434/v1/chat/completions'
});
db.model_datas.insertOne({
  _id: '3',
  model: 'deepseek-r1:8b',
  name: 'DeepSeek-R1-8B (Ollama)',
  avatar: '/imgs/model/openai.svg',
  maxContext: 32768,
  maxResponse: 8000,
  quoteMaxToken: 3000,
  maxTemperature: 1.2,
  charsPointsPrice: 0,
  censor: true,
  vision: false,
  datasetProcess: true,
  usedInClassify: true,
  usedInExtractFields: true,
  usedInToolCall: true,
  usedInQueryExtension: true,
  toolChoice: true,
  functionCall: true,
  dbModel: 'deepseek-r1:8b',
  dbMaxToken: 8000,
  dbReqUrl: 'http://localhost:11434/v1/chat/completions'
});
db.model_datas.insertOne({
  _id: '4',
  model: 'llama3:8b',
  name: 'Llama3-8B (Ollama)',
  avatar: '/imgs/model/openai.svg',
  maxContext: 8192,
  maxResponse: 4000,
  quoteMaxToken: 3000,
  maxTemperature: 1.2,
  charsPointsPrice: 0,
  censor: true,
  vision: false,
  datasetProcess: true,
  usedInClassify: true,
  usedInExtractFields: true,
  usedInToolCall: true,
  usedInQueryExtension: true,
  toolChoice: true,
  functionCall: true,
  dbModel: 'llama3:8b',
  dbMaxToken: 4000,
  dbReqUrl: 'http://localhost:11434/v1/chat/completions'
});
db.model_datas.insertOne({
  _id: '5',
  model: 'qwen2:7b',
  name: '通义千问2-7B (Ollama)',
  avatar: '/imgs/model/openai.svg',
  maxContext: 32768,
  maxResponse: 8000,
  quoteMaxToken: 3000,
  maxTemperature: 1.2,
  charsPointsPrice: 0,
  censor: true,
  vision: false,
  datasetProcess: true,
  usedInClassify: true,
  usedInExtractFields: true,
  usedInToolCall: true,
  usedInQueryExtension: true,
  toolChoice: true,
  functionCall: true,
  dbModel: 'qwen2:7b',
  dbMaxToken: 8000,
  dbReqUrl: 'http://localhost:11434/v1/chat/completions'
});
db.model_datas.insertOne({
  _id: '6',
  model: 'embedding-2',
  name: '智谱Embedding-2',
  avatar: '/imgs/model/embedding.svg',
  maxToken: 3000,
  defaultToken: 700,
  weight: 100,
  dbModel: 'embedding-2',
  dbRequestUrl: ''
});
db.model_datas.insertOne({
  _id: '7',
  model: 'bge-m3:latest',
  name: 'BGE-M3 (Ollama)',
  avatar: '/imgs/model/embedding.svg',
  maxToken: 8192,
  defaultToken: 700,
  weight: 100,
  dbModel: 'bge-m3:latest',
  dbRequestUrl: 'http://localhost:11434/v1/embeddings'
});
db.model_datas.insertOne({
  _id: '8',
  model: 'mxbai-embed-large:latest',
  name: 'MXBAI-Large (Ollama)',
  avatar: '/imgs/model/embedding.svg',
  maxToken: 512,
  defaultToken: 700,
  weight: 100,
  dbModel: 'mxbai-embed-large:latest',
  dbRequestUrl: 'http://localhost:11434/v1/embeddings'
});
print('Imported', db.model_datas.countDocuments({}), 'models');
